[pytest]
testpaths = api_tests/testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -s --alluredir=api_tests/reports/allure-results
cache_dir = api_tests/reports/.pytest_cache
markers =
    excel: tests loaded from Excel case files
