# Generated by Django 4.2.7 on 2026-06-04 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_no', models.CharField(db_index=True, max_length=32, unique=True)),
                ('product_code', models.CharField(max_length=32)),
                ('product_name', models.CharField(max_length=128)),
                ('plan_code', models.CharField(max_length=32)),
                ('plan_name', models.CharField(max_length=128)),
                ('applicant', models.JSONField()),
                ('insured', models.JSONField()),
                ('coverages', models.JSONField()),
                ('premium_detail', models.JSONField()),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('QUOTED', '已试算'), ('UNDERWRITTEN', '已核保'), ('ISSUED', '已出单'), ('EXPIRED', '已失效')], default='QUOTED', max_length=20)),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnderwritingCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uw_no', models.CharField(db_index=True, max_length=32, unique=True)),
                ('decision', models.CharField(choices=[('APPROVED', '通过'), ('REFERRED', '转人工'), ('DECLINED', '拒保')], max_length=20)),
                ('risk_level', models.CharField(max_length=16)),
                ('reasons', models.JSONField(default=list)),
                ('disclosures', models.JSONField()),
                ('manual_review_required', models.BooleanField(default=False)),
                ('valid_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='underwriting_cases', to='insurance.premiumquote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_no', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('ISSUED', '已承保'), ('CANCELLED', '已撤单')], default='ISSUED', max_length=20)),
                ('applicant', models.JSONField()),
                ('insured', models.JSONField()),
                ('coverages', models.JSONField()),
                ('premium_detail', models.JSONField()),
                ('payment', models.JSONField()),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='policy', to='insurance.premiumquote')),
                ('underwriting', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='policy', to='insurance.underwritingcase')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
    ]
