# Generated by Django 4.2.7 on 2026-06-04 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-issued_at'], 'verbose_name': '保单', 'verbose_name_plural': '保单'},
        ),
        migrations.AlterModelOptions(
            name='premiumquote',
            options={'ordering': ['-created_at'], 'verbose_name': '保费试算单', 'verbose_name_plural': '保费试算单'},
        ),
        migrations.AlterModelOptions(
            name='underwritingcase',
            options={'ordering': ['-created_at'], 'verbose_name': '核保记录', 'verbose_name_plural': '核保记录'},
        ),
        migrations.AlterModelTableComment(
            name='policy',
            table_comment='保单表',
        ),
        migrations.AlterModelTableComment(
            name='premiumquote',
            table_comment='保费试算单表',
        ),
        migrations.AlterModelTableComment(
            name='underwritingcase',
            table_comment='核保记录表',
        ),
        migrations.AlterField(
            model_name='policy',
            name='applicant',
            field=models.JSONField(db_comment='投保人信息', verbose_name='投保人信息'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='coverages',
            field=models.JSONField(db_comment='保障责任', verbose_name='保障责任'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='effective_date',
            field=models.DateField(db_comment='保险起期', verbose_name='保险起期'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='expiry_date',
            field=models.DateField(db_comment='保险止期', verbose_name='保险止期'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='insured',
            field=models.JSONField(db_comment='被保人信息', verbose_name='被保人信息'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='出单时间', verbose_name='出单时间'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='payment',
            field=models.JSONField(db_comment='支付信息', verbose_name='支付信息'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_no',
            field=models.CharField(db_comment='保单号', db_index=True, max_length=32, unique=True, verbose_name='保单号'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='premium_detail',
            field=models.JSONField(db_comment='保费明细', verbose_name='保费明细'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='quote',
            field=models.OneToOneField(db_comment='关联试算单', on_delete=django.db.models.deletion.PROTECT, related_name='policy', to='insurance.premiumquote', verbose_name='关联试算单'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('ISSUED', '已承保'), ('CANCELLED', '已撤单')], db_comment='保单状态', default='ISSUED', max_length=20, verbose_name='保单状态'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='underwriting',
            field=models.OneToOneField(db_comment='关联核保记录', on_delete=django.db.models.deletion.PROTECT, related_name='policy', to='insurance.underwritingcase', verbose_name='关联核保记录'),
        ),
        migrations.AlterField(
            model_name='premiumquote',
            name='applicant',
            field=models.JSONField(db_comment='投保人信息', verbose_name='投保人信息'),
        ),
        migrations.AlterField(
            model_name='premiumquote',
            name='coverages',
            field=models.JSONField(db_comment='保障责任', verbose_name='保障责任'),
        ),
        migrations.AlterField(
            model_name='premiumquote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='premiumquote',
            name='effective_date',
            field=models.DateField(db_comment='保险起期', verbose_name='保险起期'),
        ),
        migrations.AlterField(
            model_name='premiumquote',
            name='expiry_date',
            field=models.DateField(db_comment='保险止期', verbose_name='保险止期'),
        ),
        migrations.AlterField(
            model_name='premiumquote',
            name='insured',
            field=models.JSONField(db_comment='被保人信息', verbose_name='被保人信息'),
        ),
        migrations.AlterField(
            model_name='premiumquote',
            name='plan_code',
            field=models.CharField(db_comment='计划代码', max_length=32, verbose_name='计划代码'),
        ),
        migrations.AlterField(
            model_name='premiumquote',
            name='plan_name',
            field=models.CharField(db_comment='计划名称', max_length=128, verbose_name='计划名称'),
        ),
        migrations.AlterField(
            model_name='premiumquote',
            name='premium_detail',
            field=models.JSONField(db_comment='保费明细', verbose_name='保费明细'),
        ),
        migrations.AlterField(
            model_name='premiumquote',
            name='product_code',
            field=models.CharField(db_comment='产品代码', max_length=32, verbose_name='产品代码'),
        ),
        migrations.AlterField(
            model_name='premiumquote',
            name='product_name',
            field=models.CharField(db_comment='产品名称', max_length=128, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='premiumquote',
            name='quote_no',
            field=models.CharField(db_comment='试算单号', db_index=True, max_length=32, unique=True, verbose_name='试算单号'),
        ),
        migrations.AlterField(
            model_name='premiumquote',
            name='status',
            field=models.CharField(choices=[('QUOTED', '已试算'), ('UNDERWRITTEN', '已核保'), ('ISSUED', '已出单'), ('EXPIRED', '已失效')], db_comment='试算状态', default='QUOTED', max_length=20, verbose_name='试算状态'),
        ),
        migrations.AlterField(
            model_name='premiumquote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='premiumquote',
            name='valid_until',
            field=models.DateTimeField(db_comment='有效截止时间', verbose_name='有效截止时间'),
        ),
        migrations.AlterField(
            model_name='underwritingcase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='underwritingcase',
            name='decision',
            field=models.CharField(choices=[('APPROVED', '通过'), ('REFERRED', '转人工'), ('DECLINED', '拒保')], db_comment='核保结论', max_length=20, verbose_name='核保结论'),
        ),
        migrations.AlterField(
            model_name='underwritingcase',
            name='disclosures',
            field=models.JSONField(db_comment='告知信息', verbose_name='告知信息'),
        ),
        migrations.AlterField(
            model_name='underwritingcase',
            name='manual_review_required',
            field=models.BooleanField(db_comment='是否人工核保', default=False, verbose_name='是否人工核保'),
        ),
        migrations.AlterField(
            model_name='underwritingcase',
            name='quote',
            field=models.ForeignKey(db_comment='关联试算单', on_delete=django.db.models.deletion.PROTECT, related_name='underwriting_cases', to='insurance.premiumquote', verbose_name='关联试算单'),
        ),
        migrations.AlterField(
            model_name='underwritingcase',
            name='reasons',
            field=models.JSONField(db_comment='核保原因', default=list, verbose_name='核保原因'),
        ),
        migrations.AlterField(
            model_name='underwritingcase',
            name='risk_level',
            field=models.CharField(db_comment='风险等级', max_length=16, verbose_name='风险等级'),
        ),
        migrations.AlterField(
            model_name='underwritingcase',
            name='uw_no',
            field=models.CharField(db_comment='核保单号', db_index=True, max_length=32, unique=True, verbose_name='核保单号'),
        ),
        migrations.AlterField(
            model_name='underwritingcase',
            name='valid_until',
            field=models.DateTimeField(db_comment='有效截止时间', verbose_name='有效截止时间'),
        ),
    ]
