# Generated by Django 4.2.7 on 2026-06-05 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_policy_options_alter_premiumquote_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(db_comment='投保单号', db_index=True, max_length=32, unique=True, verbose_name='投保单号')),
                ('status', models.CharField(choices=[('CREATED', '已创建'), ('SUBMITTED', '已提交'), ('UNDERWRITING_APPROVED', '核保通过'), ('UNDERWRITING_REFERRED', '待人工核保'), ('UNDERWRITING_DECLINED', '核保拒保'), ('PAYMENT_PENDING', '待支付'), ('PAID', '已支付'), ('ISSUED', '已出单'), ('CLOSED', '已关闭')], db_comment='投保单状态', default='CREATED', max_length=32, verbose_name='投保单状态')),
                ('applicant', models.JSONField(db_comment='投保人信息', verbose_name='投保人信息')),
                ('insured', models.JSONField(db_comment='被保人信息', verbose_name='被保人信息')),
                ('disclosures', models.JSONField(db_comment='核保告知信息', default=dict, verbose_name='核保告知信息')),
                ('beneficiary_type', models.CharField(db_comment='LEGAL 法定；DESIGNATED 指定', default='LEGAL', max_length=16, verbose_name='受益人类型')),
                ('beneficiaries', models.JSONField(db_comment='指定受益人列表', default=list, verbose_name='指定受益人列表')),
                ('consents', models.JSONField(db_comment='条款、免责、电子保单等确认留痕', default=dict, verbose_name='投保确认信息')),
                ('channel_code', models.CharField(db_comment='渠道代码', max_length=32, verbose_name='渠道代码')),
                ('submitted_at', models.DateTimeField(blank=True, db_comment='提交核保时间', null=True, verbose_name='提交时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间')),
                ('quote', models.OneToOneField(db_comment='关联试算单', on_delete=django.db.models.deletion.PROTECT, related_name='application', to='insurance.premiumquote', verbose_name='关联试算单')),
            ],
            options={
                'verbose_name': '投保单',
                'verbose_name_plural': '投保单',
                'db_table_comment': '投保单表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_order_no', models.CharField(db_comment='支付订单号', db_index=True, max_length=32, unique=True, verbose_name='支付订单号')),
                ('amount', models.DecimalField(db_comment='应付金额', decimal_places=2, max_digits=10, verbose_name='应付金额')),
                ('status', models.CharField(choices=[('CREATED', '已创建'), ('SUCCESS', '支付成功'), ('FAILED', '支付失败'), ('CLOSED', '已关闭')], db_comment='支付状态', default='CREATED', max_length=20, verbose_name='支付状态')),
                ('pay_channel', models.CharField(db_comment='支付渠道', default='MOCK', max_length=32, verbose_name='支付渠道')),
                ('external_trade_no', models.CharField(blank=True, db_comment='外部交易流水号', max_length=64, verbose_name='外部交易流水号')),
                ('notify_payload', models.JSONField(db_comment='支付通知原文', default=dict, verbose_name='支付通知原文')),
                ('paid_at', models.DateTimeField(blank=True, db_comment='支付成功时间', null=True, verbose_name='支付成功时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间')),
                ('application', models.ForeignKey(db_comment='关联投保单', on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='insurance.insuranceapplication', verbose_name='关联投保单')),
                ('quote', models.ForeignKey(db_comment='关联试算单', on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='insurance.premiumquote', verbose_name='关联试算单')),
                ('underwriting', models.ForeignKey(db_comment='关联核保记录', on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='insurance.underwritingcase', verbose_name='关联核保记录')),
            ],
            options={
                'verbose_name': '支付订单',
                'verbose_name_plural': '支付订单',
                'db_table_comment': '支付订单表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualUnderwritingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_no', models.CharField(db_comment='人工核保单号', db_index=True, max_length=32, unique=True, verbose_name='人工核保单号')),
                ('decision', models.CharField(choices=[('APPROVED', '通过'), ('REFERRED', '转人工'), ('DECLINED', '拒保')], db_comment='人工核保结论', max_length=20, verbose_name='人工核保结论')),
                ('risk_level', models.CharField(db_comment='人工评定风险等级', max_length=16, verbose_name='人工评定风险等级')),
                ('reasons', models.JSONField(db_comment='人工核保原因', default=list, verbose_name='人工核保原因')),
                ('review_notes', models.TextField(blank=True, db_comment='复核备注', verbose_name='复核备注')),
                ('reviewer', models.CharField(db_comment='复核人员', max_length=64, verbose_name='复核人员')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, db_comment='复核时间', verbose_name='复核时间')),
                ('underwriting', models.OneToOneField(db_comment='关联核保记录', on_delete=django.db.models.deletion.PROTECT, related_name='manual_review', to='insurance.underwritingcase', verbose_name='关联核保记录')),
            ],
            options={
                'verbose_name': '人工核保复核记录',
                'verbose_name_plural': '人工核保复核记录',
                'db_table_comment': '人工核保复核记录表',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_no', models.CharField(db_comment='电子保单文档号', db_index=True, max_length=32, unique=True, verbose_name='电子保单文档号')),
                ('download_url', models.CharField(db_comment='电子保单下载地址', max_length=256, verbose_name='下载地址')),
                ('verify_code', models.CharField(db_comment='电子保单验真码', max_length=32, verbose_name='验真码')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_comment='生成时间', verbose_name='生成时间')),
                ('policy', models.OneToOneField(db_comment='关联保单', on_delete=django.db.models.deletion.PROTECT, related_name='electronic_policy', to='insurance.policy', verbose_name='关联保单')),
            ],
            options={
                'verbose_name': '电子保单',
                'verbose_name_plural': '电子保单',
                'db_table_comment': '电子保单表',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_no', models.CharField(db_comment='送达流水号', db_index=True, max_length=32, unique=True, verbose_name='送达流水号')),
                ('channel', models.CharField(choices=[('EMAIL', '邮件'), ('SMS', '短信')], db_comment='送达渠道', max_length=16, verbose_name='送达渠道')),
                ('recipient', models.CharField(db_comment='邮箱或手机号', max_length=128, verbose_name='收件人')),
                ('status', models.CharField(choices=[('SENT', '已发送'), ('FAILED', '发送失败')], db_comment='送达状态', default='SENT', max_length=16, verbose_name='送达状态')),
                ('payload', models.JSONField(db_comment='送达内容', default=dict, verbose_name='送达内容')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_comment='发送时间', verbose_name='发送时间')),
                ('policy', models.ForeignKey(db_comment='关联保单', on_delete=django.db.models.deletion.PROTECT, related_name='delivery_records', to='insurance.policy', verbose_name='关联保单')),
            ],
            options={
                'verbose_name': '电子保单送达记录',
                'verbose_name_plural': '电子保单送达记录',
                'db_table_comment': '电子保单送达记录表',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='application',
            field=models.OneToOneField(blank=True, db_comment='关联投保单；兼容旧出单接口时允许为空', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy', to='insurance.insuranceapplication', verbose_name='关联投保单'),
        ),
        migrations.AddField(
            model_name='policy',
            name='payment_order',
            field=models.OneToOneField(blank=True, db_comment='关联支付订单；兼容旧出单接口时允许为空', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policy', to='insurance.paymentorder', verbose_name='关联支付订单'),
        ),
        migrations.AddField(
            model_name='underwritingcase',
            name='application',
            field=models.ForeignKey(blank=True, db_comment='关联投保单；兼容旧试算核保接口时允许为空', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='underwriting_cases', to='insurance.insuranceapplication', verbose_name='关联投保单'),
        ),
    ]
