# Generated by Django 4.2.7 on 2026-06-06 04:33

from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion


def seed_default_product_config(apps, schema_editor):
    Product = apps.get_model('insurance', 'Product')
    ProductPlan = apps.get_model('insurance', 'ProductPlan')
    ProductCoverage = apps.get_model('insurance', 'ProductCoverage')
    AgeRateFactor = apps.get_model('insurance', 'AgeRateFactor')
    OccupationRateFactor = apps.get_model('insurance', 'OccupationRateFactor')

    product, _ = Product.objects.update_or_create(
        product_code='PA_C_ACCIDENT',
        defaults={
            'product_name': '平安个人综合意外险',
            'description': '示例个人综合意外险产品，覆盖意外身故/伤残、意外医疗、意外住院津贴等责任。',
            'status': 'ACTIVE',
            'min_age': 0,
            'max_age': 65,
            'min_period_months': 1,
            'max_period_months': 12,
        },
    )

    plans = [
        (
            'BASIC',
            '基础版',
            Decimal('99.00'),
            1,
            [
                ('ACCIDENT_DEATH', '意外身故/伤残', Decimal('100000.00'), 1),
                ('ACCIDENT_MEDICAL', '意外医疗', Decimal('10000.00'), 2),
            ],
        ),
        (
            'STANDARD',
            '标准版',
            Decimal('199.00'),
            2,
            [
                ('ACCIDENT_DEATH', '意外身故/伤残', Decimal('300000.00'), 1),
                ('ACCIDENT_MEDICAL', '意外医疗', Decimal('30000.00'), 2),
                ('HOSPITAL_ALLOWANCE', '意外住院津贴', Decimal('100.00'), 3),
            ],
        ),
        (
            'PREMIUM',
            '尊享版',
            Decimal('399.00'),
            3,
            [
                ('ACCIDENT_DEATH', '意外身故/伤残', Decimal('800000.00'), 1),
                ('ACCIDENT_MEDICAL', '意外医疗', Decimal('80000.00'), 2),
                ('HOSPITAL_ALLOWANCE', '意外住院津贴', Decimal('200.00'), 3),
            ],
        ),
    ]
    for plan_code, plan_name, base_premium, sort_order, coverages in plans:
        plan, _ = ProductPlan.objects.update_or_create(
            product=product,
            plan_code=plan_code,
            defaults={
                'plan_name': plan_name,
                'base_premium': base_premium,
                'is_enabled': True,
                'sort_order': sort_order,
            },
        )
        for coverage_code, coverage_name, insured_amount, coverage_sort in coverages:
            ProductCoverage.objects.update_or_create(
                plan=plan,
                coverage_code=coverage_code,
                defaults={
                    'coverage_name': coverage_name,
                    'insured_amount': insured_amount,
                    'sort_order': coverage_sort,
                },
            )

    for min_age, max_age, factor in [
        (0, 17, Decimal('0.8000')),
        (18, 45, Decimal('1.0000')),
        (46, 60, Decimal('1.3500')),
        (61, 120, Decimal('1.8000')),
    ]:
        AgeRateFactor.objects.update_or_create(
            product=product,
            min_age=min_age,
            max_age=max_age,
            defaults={'factor': factor, 'is_enabled': True},
        )

    for occupation_category, factor in [
        (1, Decimal('0.9000')),
        (2, Decimal('1.0000')),
        (3, Decimal('1.2000')),
        (4, Decimal('1.6000')),
        (5, Decimal('2.5000')),
        (6, Decimal('3.5000')),
    ]:
        OccupationRateFactor.objects.update_or_create(
            product=product,
            occupation_category=occupation_category,
            defaults={'factor': factor, 'is_enabled': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_insuranceapplication_paymentorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(db_comment='产品代码', db_index=True, max_length=32, unique=True, verbose_name='产品代码')),
                ('product_name', models.CharField(db_comment='产品名称', max_length=128, verbose_name='产品名称')),
                ('description', models.TextField(blank=True, db_comment='产品详情', verbose_name='产品详情')),
                ('status', models.CharField(choices=[('ACTIVE', '在售'), ('INACTIVE', '停售')], db_comment='产品状态', default='ACTIVE', max_length=16, verbose_name='产品状态')),
                ('min_age', models.PositiveSmallIntegerField(db_comment='最小承保年龄', default=0, verbose_name='最小承保年龄')),
                ('max_age', models.PositiveSmallIntegerField(db_comment='最大承保年龄', default=65, verbose_name='最大承保年龄')),
                ('min_period_months', models.PositiveSmallIntegerField(db_comment='最短保障期限（月）', default=1, verbose_name='最短保障期限（月）')),
                ('max_period_months', models.PositiveSmallIntegerField(db_comment='最长保障期限（月）', default=12, verbose_name='最长保障期限（月）')),
                ('effective_start', models.DateField(blank=True, db_comment='销售起期', null=True, verbose_name='销售起期')),
                ('effective_end', models.DateField(blank=True, db_comment='销售止期', null=True, verbose_name='销售止期')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '保险产品',
                'verbose_name_plural': '保险产品',
                'db_table_comment': '保险产品配置表',
                'ordering': ['product_code'],
            },
        ),
        migrations.CreateModel(
            name='ProductPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(db_comment='计划代码', max_length=32, verbose_name='计划代码')),
                ('plan_name', models.CharField(db_comment='计划名称', max_length=128, verbose_name='计划名称')),
                ('base_premium', models.DecimalField(db_comment='基础保费', decimal_places=2, max_digits=10, verbose_name='基础保费')),
                ('is_enabled', models.BooleanField(db_comment='是否启用', default=True, verbose_name='是否启用')),
                ('sort_order', models.PositiveSmallIntegerField(db_comment='排序', default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新时间', verbose_name='更新时间')),
                ('product', models.ForeignKey(db_comment='所属产品', on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='insurance.product', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': '保险计划',
                'verbose_name_plural': '保险计划',
                'db_table_comment': '保险计划配置表',
                'ordering': ['product__product_code', 'sort_order', 'plan_code'],
                'unique_together': {('product', 'plan_code')},
            },
        ),
        migrations.CreateModel(
            name='AgeRateFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.PositiveSmallIntegerField(db_comment='最小年龄', verbose_name='最小年龄')),
                ('max_age', models.PositiveSmallIntegerField(db_comment='最大年龄', verbose_name='最大年龄')),
                ('factor', models.DecimalField(db_comment='费率系数', decimal_places=4, max_digits=8, verbose_name='费率系数')),
                ('is_enabled', models.BooleanField(db_comment='是否启用', default=True, verbose_name='是否启用')),
                ('product', models.ForeignKey(db_comment='所属产品', on_delete=django.db.models.deletion.PROTECT, related_name='age_rate_factors', to='insurance.product', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': '年龄费率因子',
                'verbose_name_plural': '年龄费率因子',
                'db_table_comment': '年龄费率因子表',
                'ordering': ['product__product_code', 'min_age'],
            },
        ),
        migrations.CreateModel(
            name='ProductCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_code', models.CharField(db_comment='责任代码', max_length=32, verbose_name='责任代码')),
                ('coverage_name', models.CharField(db_comment='责任名称', max_length=128, verbose_name='责任名称')),
                ('insured_amount', models.DecimalField(db_comment='保额', decimal_places=2, max_digits=12, verbose_name='保额')),
                ('description', models.CharField(blank=True, db_comment='责任说明', max_length=256, verbose_name='责任说明')),
                ('sort_order', models.PositiveSmallIntegerField(db_comment='排序', default=0, verbose_name='排序')),
                ('plan', models.ForeignKey(db_comment='所属计划', on_delete=django.db.models.deletion.PROTECT, related_name='coverages', to='insurance.productplan', verbose_name='所属计划')),
            ],
            options={
                'verbose_name': '保障责任',
                'verbose_name_plural': '保障责任',
                'db_table_comment': '保障责任配置表',
                'ordering': ['plan', 'sort_order', 'coverage_code'],
                'unique_together': {('plan', 'coverage_code')},
            },
        ),
        migrations.CreateModel(
            name='OccupationRateFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_category', models.PositiveSmallIntegerField(db_comment='职业类别', verbose_name='职业类别')),
                ('factor', models.DecimalField(db_comment='费率系数', decimal_places=4, max_digits=8, verbose_name='费率系数')),
                ('is_enabled', models.BooleanField(db_comment='是否启用', default=True, verbose_name='是否启用')),
                ('product', models.ForeignKey(db_comment='所属产品', on_delete=django.db.models.deletion.PROTECT, related_name='occupation_rate_factors', to='insurance.product', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': '职业费率因子',
                'verbose_name_plural': '职业费率因子',
                'db_table_comment': '职业费率因子表',
                'ordering': ['product__product_code', 'occupation_category'],
                'unique_together': {('product', 'occupation_category')},
            },
        ),
        migrations.RunPython(seed_default_product_config, migrations.RunPython.noop),
    ]
